# Generated by Django 5.2.1 on 2025-06-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-create_date'], 'verbose_name': 'Customer Inquiry', 'verbose_name_plural': 'Customer Inquiries'},
        ),
        migrations.AddField(
            model_name='contact',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Enter your reply to the customer here', null=True, verbose_name='Admin Reply'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Check this box when the inquiry is handled', verbose_name='Mark as Resolved'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reply Date'),
        ),
    ]
