# Generated by Django 5.2.1 on 2025-05-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('KO', 'Koshi'), ('MA', 'Madhesh'), ('BA', 'Bagmati'), ('GA', 'Gandaki'), ('LI', 'Lumbini,'), ('KA', 'Karnali'), ('SU', 'Sudurpaschim')], max_length=100),
        ),
    ]
