# Generated by Django 5.2.1 on 2025-05-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
