# Generated by Django 5.2.1 on 2025-05-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_latitude_car_longitude_car_place_car_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='province',
        ),
    ]
