# Generated by Django 5.2.1 on 2025-05-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('KO', 'Koshi'), ('MA', 'Madhesh'), ('BA', 'Bagmati'), ('GA', 'Gandaki'), ('LI', 'Lumbini'), ('KA', 'Karnali'), ('SU', 'Sudurpaschim')], max_length=100),
        ),
    ]
