# Generated by Django 5.2.1 on 2025-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_reservation_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
