# Generated by Django 5.2.1 on 2025-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_reservation_delivery_address_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driven_wheels',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_cylinders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='market_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
