# Generated by Django 5.2.1 on 2025-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_car_driven_wheels_car_engine_cylinders_car_make_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fuel_type',
            new_name='engine_fuel_type',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='doors',
            new_name='number_of_doors',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='body_style',
            new_name='transmission_type',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='engine',
            new_name='vehicle_style',
        ),
        migrations.RemoveField(
            model_name='car',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='car',
            name='milage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='highway_mpg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
