# Generated by Django 5.2.1 on 2025-06-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_rename_fuel_type_car_engine_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='msrp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
